const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = window.APP_CONFIG;
const db = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
let currentUser=null,currentProfile=null,articlesCache=[],ordersCache=[];
const $=(id)=>document.getElementById(id);const loginView=$("login-view"),appView=$("app-view"),loginForm=$("login-form"),loginError=$("login-error"),logoutBtn=$("logout-btn"),menuToggle=$("menu-toggle"),sidebar=document.querySelector(".sidebar");
const money=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"});const numberFmt=new Intl.NumberFormat("it-IT",{maximumFractionDigits:3});
function showToast(message){const toast=$("toast");toast.textContent=message;toast.classList.remove("hidden");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.add("hidden"),2600)}
function escapeHtml(value=""){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function statusLabel(status){return({open:"Aperta",in_progress:"In corso",completed:"Completata",cancelled:"Annullata"})[status]||status}
async function loadProfile(){const{data,error}=await db.from("profiles").select("id, full_name, role").eq("id",currentUser.id).single();if(error)throw error;currentProfile=data}
function applyRoleUI(){const role=currentProfile?.role||"operator";$("role-label").textContent=role==="master"?"Master":"Operatore";$("user-name").textContent=currentProfile?.full_name?.trim()||"Utente";$("user-email").textContent=currentUser?.email||"";document.querySelectorAll(".master-only").forEach(el=>el.classList.toggle("hidden",role!=="master"))}
async function enterApp(user){currentUser=user;await loadProfile();applyRoleUI();loginView.classList.add("hidden");appView.classList.remove("hidden");await Promise.all([loadArticles(),loadOrders()]);renderDashboard()}
function leaveApp(){currentUser=null;currentProfile=null;articlesCache=[];ordersCache=[];appView.classList.add("hidden");loginView.classList.remove("hidden");loginForm.reset()}
loginForm.addEventListener("submit",async event=>{event.preventDefault();loginError.classList.add("hidden");const button=$("login-btn");button.disabled=true;button.textContent="Accesso...";const{data,error}=await db.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});button.disabled=false;button.textContent="Accedi";if(error){loginError.textContent="Email o password non corretti.";loginError.classList.remove("hidden");return}try{await enterApp(data.user)}catch(err){console.error(err);loginError.textContent="Accesso riuscito, ma non riesco a caricare il profilo.";loginError.classList.remove("hidden")}});
logoutBtn.addEventListener("click",async()=>{await db.auth.signOut();leaveApp()});
document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>{const target=button.dataset.section;document.querySelectorAll(".nav-item").forEach(b=>b.classList.remove("active"));button.classList.add("active");document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));$(`section-${target}`).classList.add("active");$("page-title").textContent=({dashboard:"Dashboard",articles:"Articoli",orders:"Lavorazioni"})[target]||"Magazzino";sidebar.classList.remove("open")}));menuToggle?.addEventListener("click",()=>sidebar.classList.toggle("open"));
async function loadArticles(){const{data,error}=await db.from("articles").select("id, code, description, quantity, unit_price, unit, created_at").order("description",{ascending:true});if(error){console.error(error);showToast("Errore nel caricamento degli articoli");return}articlesCache=data||[];renderArticles()}
function renderArticles(){const query=$("article-search").value.trim().toLowerCase();const rows=articlesCache.filter(a=>!query||a.code.toLowerCase().includes(query)||a.description.toLowerCase().includes(query));$("articles-body").innerHTML=rows.map(a=>`<tr><td><strong>${escapeHtml(a.code)}</strong></td><td>${escapeHtml(a.description)}</td><td>${numberFmt.format(Number(a.quantity||0))}</td><td>${escapeHtml(a.unit)}</td><td>${money.format(Number(a.unit_price||0))}</td></tr>`).join("");$("articles-empty").classList.toggle("hidden",rows.length>0)}
$("article-search").addEventListener("input",renderArticles);$("new-article-btn").addEventListener("click",()=>{$("article-form").reset();$("article-quantity").value="0";$("article-unit").value="pz";$("article-price").value="0";$("article-dialog").showModal()});
$("article-form").addEventListener("submit",async event=>{event.preventDefault();const payload={code:$("article-code").value.trim(),description:$("article-description").value.trim(),quantity:Number($("article-quantity").value),unit:$("article-unit").value.trim()||"pz",unit_price:Number($("article-price").value)};const{error}=await db.from("articles").insert(payload);if(error){console.error(error);showToast(error.code==="23505"?"Codice articolo già esistente":"Errore nel salvataggio");return}$("article-dialog").close();showToast("Articolo creato");await loadArticles();renderDashboard()});
async function loadOrders(){const{data,error}=await db.from("work_orders").select("id, code, description, status, created_at, completed_at").order("created_at",{ascending:false});if(error){console.error(error);showToast("Errore nel caricamento delle lavorazioni");return}ordersCache=data||[];renderOrders()}
function renderOrders(){const filter=$("order-filter").value;const rows=ordersCache.filter(o=>filter==="all"||o.status===filter);$("orders-list").innerHTML=rows.map(o=>`<article class="order-card"><div><h4>${escapeHtml(o.description)}</h4><div class="muted">${escapeHtml(o.code)}</div><div class="order-meta"><span class="badge ${escapeHtml(o.status)}">${statusLabel(o.status)}</span><span class="badge">${new Date(o.created_at).toLocaleDateString("it-IT")}</span></div></div></article>`).join("");$("orders-empty").classList.toggle("hidden",rows.length>0)}
$("order-filter").addEventListener("change",renderOrders);$("new-order-btn").addEventListener("click",()=>{$("order-form").reset();$("order-dialog").showModal()});
$("order-form").addEventListener("submit",async event=>{event.preventDefault();const payload={code:$("order-code").value.trim(),description:$("order-description").value.trim(),status:"open"};const{error}=await db.from("work_orders").insert(payload);if(error){console.error(error);showToast(error.code==="23505"?"Codice lavorazione già esistente":"Errore nella creazione");return}$("order-dialog").close();showToast("Lavorazione creata");await loadOrders();renderDashboard()});
document.querySelectorAll("[data-close-dialog]").forEach(button=>button.addEventListener("click",()=>$(button.dataset.closeDialog)?.close()));
function renderDashboard(){$("stat-articles").textContent=numberFmt.format(articlesCache.length);$("stat-open-orders").textContent=numberFmt.format(ordersCache.filter(o=>["open","in_progress"].includes(o.status)).length);$("stat-completed-orders").textContent=numberFmt.format(ordersCache.filter(o=>o.status==="completed").length);const stockValue=articlesCache.reduce((sum,a)=>sum+Number(a.quantity||0)*Number(a.unit_price||0),0);$("stat-stock-value").textContent=money.format(stockValue);const recent=ordersCache.slice(0,5);$("recent-orders").innerHTML=recent.length?recent.map(o=>`<div class="order-card"><div><strong>${escapeHtml(o.description)}</strong><div class="muted">${escapeHtml(o.code)}</div></div><span class="badge ${escapeHtml(o.status)}">${statusLabel(o.status)}</span></div>`).join(""):`<div class="empty">Nessuna lavorazione presente.</div>`}
async function boot(){const{data:{session}}=await db.auth.getSession();if(session?.user){try{await enterApp(session.user)}catch(err){console.error(err);await db.auth.signOut();leaveApp()}}else leaveApp();if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error)}boot();